In [1]:
%pylab inline
import warnings
warnings.filterwarnings('ignore')

Populating the interactive namespace from numpy and matplotlib


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.corpus import stopwords

In [3]:
reviews = pd.read_csv('reviews_restaurants_text.csv')
reviews['text'] = reviews['text'].str[2:-2]
review1 = reviews[reviews['stars'] == 1][0:12000]
review2 = reviews[reviews['stars'] == 2][0:7000]
review3 = reviews[reviews['stars'] == 3][0:12000]
review4 = reviews[reviews['stars'] == 4][0:12000]
review5 = reviews[reviews['stars'] == 5][0:12000]
frames = [review1, review2, review3,review4,review5]
reviews = pd.concat(frames)
reviews

review_id             business_id                 user_id  \
1      xryg94pDLOO71veGcQINuQ  dfRAK2mgdHbL2_YsFqtCdQ  tL2pS5UOmN6aAOi3Z-qFGg   
14     fx0AFrBZ1246jKGLKBgtMA  VPO8pBUwYz1u6GoG0d2U-Q  Tr1ulYYAHAw5FzEQQwZEJQ   
16     dH4h3Worla2GcuZxJvnlVQ  gsjxrwdHqKdTeNx3GeDKNQ  1OuFRzppeTtaEEWvc82J-A   
21     25hX4UzYNqmsy_YdTdzvjg  JyxHvtj-syke7m9rbza7mA  RFIZhrka0gCpiL62M5E93g   
23     NJjjaMAZDnB3doJvX28SJg  QIn3PuGUkinSibUn-NsljQ  V3gzoLZb9zGwfSBqGDOTXg   
48     9MbfTC06_ViQRKbsTGVeUw  ZB4ViCkUyJ4j-cJjOQ-N4A  Zqk-ye_OHeH_sS1JsdsLgg   
56     tQ8QMyGifks6J5m91io0OQ  2HxaDXZmAOH6LiuzGgNdPA  gyXhihy6SoaAIQr49MEUsA   
64     kKCtaqGn_nZHILteauNfyw  hQ4IGBbdDcCUh11zUSzwCQ  Pao1vLmA5w3zVy7GovwCOg   
114    gdsrItohw8VAYoeCCCM85A  eduRavkml8awmPachSZXuw  ktfKLUEddKApbenCdrO8tQ   
122    P8JqNKBHPRXuBB97cKCv6g  JbopSXzZIy7id23GJsO9pA  WXA_4WVO1tpD0So3pZOQQQ   
127    tBJpc1AK0MH3h09_DHGLzA  jCR-xC4NqoEajjmstqX8sA  IhfH40BJP0bhydFmCgpxMA   
151    d9PIjn3Bx4SEvB1WAB2sfA  GC5wcui5uejRZTi8OCNPkQ  6S1QxWAT9AHLdNT00iYYiQ   
169    jCpPO4ROnFfRaTwZV6LfFg  xw6G0T2VQZAtta6RcZoAOQ  mZRv579CnBtG--OheLP_bQ   
190    fLwBTdjUYit9JG9SLN1NHg  lZZLmG1ANLq2Yb3KuVA4NA  Tf6dHgeqp3uGndY72zMZrg   
193    L8Ref8iDaTL7HxHIL1JrVw  kkdm8TM6qTaVnrz5XsG0hQ  8JLQaEz0qjhKi7HFb3YhnQ   
194    hZ_iY_VG4R6RlDdfgRXcPA  DVJkxZkLKS76Khb2y6XA6A  8JLQaEz0qjhKi7HFb3YhnQ   
198    Bik0W4QiifnBZQGILt1DSA  ruPFtD9dU6Cv9_wpzIR4UQ  yHkAnD7aulxIgSOCetlGIQ   
216    UNLXHa4B_Zw1ttOoLYLYQg  Y-S2LhHefBdnX8VP5Bh_JA  LWym-jt0No9S5INdISPgUA   
240    DCkkJj0TQvU8NLLVCsc0SQ  xfWdUmrz2ha3rcigyITV0g  M_EJYPsLFYLpIkuCFZ8Wrg   
269    hEcjSZXVh1WMGS75MvfGWg  lZZLmG1ANLq2Yb3KuVA4NA  rt7gmCNCALr8bqQPluxeOQ   
271    j-nW2p085aMKfDwm6Er-uA  nQvn3VIhBqfD43Ag7QfflA  rt7gmCNCALr8bqQPluxeOQ   
285    hf5pa_GGj4c3_dZlCjSldg  e3P9dVUNlTuhlnFOZH3vAw  gESYKUY1rpYgDVcPPVY7ew   
293    dDFBNjCrDFWbsKVrziANSw  kmdFk8ETfXiuoS364jaJFA  DQYMtGFO1-DUGB0yX3a4Qg   
326    WT_jH75xy2S73tWJs7Lozw  a192hdM0_UVCYLwPJv1Qwg  by-zZnTp_37OmFDyJ62t-A   
343    v7yjWaeFH7JsZarpzcyqIA  K19uBHydrYAsfX3CPnFp-w  EbniZ0-jQTVGIA7uQk-gpA   
345    jYG5qJuDyG7ByuuscAKQ8g  hAHa78Q1os9Gvuq6Uti-0A  p85Lq9SorEmHjhLZg3l0cw   
349    LR8jdMhE0Gp_v_N71TpWLg  ZosrzTfiiPhbURA04AQTUA  p85Lq9SorEmHjhLZg3l0cw   
360    -1mNXbBNb3F4rqLi17pB2g  MZRqxvBkJLjKcoOjNz7yLA  ooIRiZCMn0N419Re-1hcVA   
391    -WaDwg-mGKuWPCStdB79xw  0_mJttUgHIzC-NO18gcgBA  ADhLuOIKgI5qYq90YwGbdQ   
412    0HpEsUCJrqJaSze3Cz8fhA  Z3ZSar8IVAR2qIupqxMynA  gd7qZfMimZ0huehA9EwTqw   
...                       ...                     ...                     ...   
21647  63mkYBe-uiIuDpxEdYbTXQ  sYfHxCqHpIX2HnDhw0JRAA  838On-g0nJaim71_tNgTBg   
21648  9IB9wikngenGME8YGh7xWA  H8umkLwMkM0vP5B8oPiozQ  838On-g0nJaim71_tNgTBg   
21649  yvLQbt47rVeZVPzzel4xKw  EAwh1OmG6t6p3nRaZOW_AA  838On-g0nJaim71_tNgTBg   
21653  DWIE6aR-YIjalK9geA20hg  Cni2l-VKG_pdospJ6xliXQ  1_YQ1OJUdFHa2_q4RH1vbw   
21654  oZmBRCKKpxCdYCSqiNW-jg  Qihead6oTtWCwde3TBqlGg  rY_vf7cAq_9Cd1btUTMOGw   
21655  WzhOMaXYAVd_HMHtkLsn3g  1XeI5PX5RxvFlaAHBKRUYA  B6cG3i52V1kaWqS2GyVZiA   
21658  wLmh0bIocuOvShkV5-Wx1Q  tgXiIcCoKYfg-hm8yLxenQ  4PQxdRCHsxyjDWeAuMdkMw   
21659  gccatcuTxKQceP3o63ZPFg  aF6cB7BtV3lXQhJoLuESGw  4PQxdRCHsxyjDWeAuMdkMw   
21660  xsANGltBaAGejGSG-764lQ  olmCDBoMF-EhN8U2livBSg  qizWMKAM-MT7StEJQ1SxCg   
21664  5AekW9UiDsjV-sLSamNQ3g  KyzPvdGPb2ubVlXJrS2QPA  CO-bhXlDRr-THlx20H4aFA   
21666  kEqrDUpTVgY8-Ma780QxCA  Q7m8G4579-XYKV3LMW8V7g  kfTyHhEg7qVGJtzJdszIMw   
21667  cLi_7nmXta6HKYg8SniXcw  s4sr0anCKMyQw53xNv6DQA  DNB5LeoYBcumQ9JILNmA9g   
21668  EXGRv1w1JqbiFF4IKzb8Iw  5PP6BwtNYlPARHApB9lzcQ  JEuC63ga3WoZVnXTA1i-oA   
21669  gLAHvPjEi2ggH-L1zG8gEg  iAu8s96GKQ73Xe7j_2GyCQ  A3Z0-Q-gOud7kHqVjrRZXA   
21670  GEdUOZw7dVOsBRFf4hJYkQ  s0vNtuLs1cwEqHTXKiS05w  26G38boY6mDMvynSz7q2uA   
21671  0TvG4FvQ_SQYpHxRGBdFUA  6xgcHeLad-VaoTIQewK84A  Z33_zUKgDyOk2lLBc9eanw   
21676  Ohgl2bZxhztdIhUjWxrqnw  v1AE1LLWDOqe8ubOzqKADg  rYrnQ3x4BeQiM8VJ5YKQXA   
21679  y5q62wjeoY0V9M0w9uLX0A  UidEFF1WpnU4duev4fjP

In [4]:
# yelp_class = reviews[(reviews['stars'] == 1) | (reviews['stars'] == 5)]
x = reviews['text']
y = reviews['stars']

In [5]:
import string
def text_process(text):
    '''
    Takes in a string of text, then performs the following:
    1. Remove all punctuation
    2. Remove all stopwords
    3. Return the cleaned text as a list of words
    '''
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
bow_transformer = CountVectorizer(analyzer=text_process).fit(x)

In [7]:
print(len(bow_transformer.vocabulary_))

47275


In [8]:
X = bow_transformer.transform(x)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [12]:
nb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [13]:
preds = nb.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix, classification_report

In [15]:
print(confusion_matrix(y_test, preds))
print('\n')
print(classification_report(y_test, preds))

[[1924  143  265   36   27]
 [ 516  171  610   71   20]
 [ 299  102 1394  477  115]
 [  84   20  481 1156  676]
 [  49    8  108  556 1692]]


             precision    recall  f1-score   support

          1       0.67      0.80      0.73      2395
          2       0.39      0.12      0.19      1388
          3       0.49      0.58      0.53      2387
          4       0.50      0.48      0.49      2417
          5       0.67      0.70      0.68      2413

avg / total       0.56      0.58      0.56     11000



In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, preds)

0.5760909090909091